[package]
name = "bag-fs"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.18"
tokio = { workspace = true, features = ["fs"] }
axum = { workspace = true }
mime_guess = "2.0.5"
tokio-util = { version = "0.7.18", features = ["io"] }
image = "0.25.10"
ffmpeg-next = "8.1.0"
zip = "8.6.0"
typed-arena = "2.0.2"
